apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
    tier: db
  name: deploy-mongo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      con: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        con: mongo
        tier: db
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
          - containerPort: 27017
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
          requests:
            memory: "400Mi"
            cpu: "200m"      
status: {}
