apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
    tier: cache
  name: deploy-redis
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      con: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        con: redis
        tier: cache
    spec:
      containers:
      - image: bitnami/redis
        name: redis
        env:
          - name: 'ALLOW_EMPTY_PASSWORD'
            value: 'yes'
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
          requests:
            memory: "400Mi"
            cpu: "200m"      
status: {}
