apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
    tier: mw
  name: svc-notes-cip
  namespace: demo
spec:
  ports:
  - port: 23456
    protocol: TCP
    targetPort: 23456
  selector:
    con: notes
  type: ClusterIP
