apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
    tier: mw
  name: svc-bugs-cip
  namespace: demo
spec:
  ports:
  - port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    con: bugs
  type: ClusterIP
