apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
    tier: cache
  name: svc-redis-cip
  namespace: demo
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    con: redis
  type: ClusterIP
